config/routes.rb
Harmonize::Application.routes.draw do
  root 'users#show'

  get '/about', to: 'main_pages#about'

  get    '/signin',  to: 'sessions#new'
  post   '/signin',  to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:new, :create, :destroy]

  resources :accounts, :users

  resources :contacts, except: :edit
  resources :events,   except: :show



  resources :tasks, except: :show do
    get :completed, on: :collection
  end

  resources :users, except: :destroy do
    get :stats, on: :member
  end

  namespace :admin do
    root 'dashboard#index'

    resources :users
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  include Nullable

  belongs_to :user

  validates_presence_of :description

  validates_length_of :description, maximum: 100

  scope :incomplete,  -> { includes(:user).where(completed: nil) }
  scope :complete,    -> { where.not(completed: nil) }
  scope :no_deadline, -> { where(deadline: nil) }

  def self.pending
    incomplete.order(deadline: :asc)
  end

  def self.completed_tasks
    complete.order(completed: :desc)
  end

  def self.overdue
    where('deadline IS NOT NULL AND deadline < ?', Time.zone.now.utc)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_signin!
  before_action :all_tasks,         only: [:index, :create, :update, :destroy]
  before_action :set_task,          only: [:edit,  :update, :destroy         ]
  after_action  :verify_authorized, only: [:create, :update, :destroy        ]
  respond_to    :html, :js

  def new
    @task = Task.new
  end

  def create
    @task      = Task.create(task_params)
    @task.user = current_user
    authorize @task
  end

  def update
    authorize @task
    @task.update_attributes(task_params)
  end

  def destroy
    authorize @task
    @task.destroy
  end

  def completed
    @tasks = Task.completed_tasks
  end

  private

    def all_tasks
      @tasks = Task.pending
    end

    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:description, :deadline, :completed, :user_id)
    end
end

app/views/tasks/_form.html.haml
= simple_form_for @task, remote: true do |f|
  %ul.errors
  .row
    .col-md-6.col-md-offset-1= f.input :description, as: :text

  .row
    .col-md-4.col-md-offset-1= f.input :deadline, as: :datetimepicker

    .col-md-4#task-form-buttons
      = hidden_field_tag 'task[user_id]', current_user.id
      = link_to 'Cancel', '#',      class: 'btn btn-default cancel'
      = f.button :submit, 'Submit', class: 'btn-default', id: 'task-submit'

app/views/tasks/_save.js.haml
= render 'shared/javascript/form_errors', klass: @task if @task.errors.any?

- unless @task.errors.any?
  $('#sort-tasks').html("#{ j render @tasks }");
  $('#task-form').slideUp(350);

app/views/tasks/_task.html.haml
= content_tag_for(:li, task, class: 'list-group-item list-group-item-info',
  'data-id' => task.id) do

  .row
    .col-md-6
      %span.task-description= task.description

    .col-md-4.task-actions.col-md-offset-2
      - if current_user.admin?

        = link_to edit_task_path(task), remote: true do
          %button.btn.btn-default.btn-xs= icon('pencil', 'Edit')

        = link_to task, remote: true, method: :delete,
          data: { confirm: 'Are you sure?' } do
          %button.btn.btn-default.btn-danger.btn-xs= icon('times', 'Delete')

        = link_to task_path(task), remote: true,
          data: { params: { task: { completed: Time.now } }.to_param,
          confirm: 'Set task as completed?' }, method: 'PATCH' do
          %button.btn.btn-default.btn-success.btn-xs= icon('check', 'Complete')

  .row
    .col-md-9
      %span.deadline
        = task_deadline(task.deadline)

    .col-md-2.col-md-offset-1
      Created by: #{task.user.handle}

app/views/tasks/_task_header.html.haml
- content_for :page_header do
  %h1 Tasks

  %nav
    %ul
      %li
        - if current_user.admin?
          = link_to admin_root_path do
            %button.header-btn.btn-1.btn-1c= icon('eye', 'Admin')
      %li
        = link_to root_path do
          %button.header-btn.btn-1.btn-1c= icon('home', 'Home')
      %li
        = link_to tasks_path do
          %button.header-btn.btn-1.btn-1c= icon('tasks', 'Pending')
      %li
        - if current_user.admin?
          = link_to completed_tasks_path do
            %button.header-btn.btn-1.btn-1c= icon('archive', 'Completed')

app/views/tasks/complete.js.haml
$('##{dom_id(@task)}').slideUp(250);

app/views/tasks/completed.html.haml
- provide(:title, 'Tasks')
= render 'task_header'

.row#completed_tasks
  %h2 Completed Tasks

.row
  %ul.list-group#completed
    - @tasks.each do |task|
      %li.list-group-item.list-group-item-success
        %i.fa.fa-check
        %ul
          %li.task-description= task.description
          %li.completed-datetime= l task.completed, format: :task_list

app/views/tasks/create.js.haml
= render 'save'

app/views/tasks/destroy.js.haml
$("#sort_tasks").html("#{ j render(@task) }");

app/views/tasks/edit.js.haml
- id = dom_id(@task)
$("##{id}").html("#{ j render 'form' }");

= render 'shared/javascript/datetimepicker'

app/views/tasks/index.html.haml
- provide(:title, 'Tasks')
= render 'task_header'

.row#tasks
  .col-md-5
    %h2 Pending Tasks
  .col-md-5.col-md-offset-2
    .task-actions
      - if current_user.admin?
        = link_to new_task_path, remote: true do
          %button.btn.btn-default= icon('plus', 'New')

.row.hidden-form#task-form{style: 'display:none;'}

.row#sort-tasks
  %ul.list-group#pending-tasks= render @tasks

app/views/tasks/new.js.haml
$('#task-form').html("#{ j render 'form' }");
$('#task-form').slideDown(350);

= render 'shared/javascript/datetimepicker'

app/views/tasks/update.js.haml
= render 'save'