config/routes.rb
Harmonize::Application.routes.draw do
  root 'users#show'

  get '/about', to: 'main_pages#about'

  get    '/signin',  to: 'sessions#new'
  post   '/signin',  to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:new, :create, :destroy]

  resources :accounts, :users

  resources :contacts, except: :edit
  resources :events,   except: :show



  resources :tasks, except: :show do
    get :completed, on: :collection
  end

  resources :users, except: :destroy do
    get :stats, on: :member
  end

  namespace :admin do
    root 'dashboard#index'

    resources :users
  end
end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :user

  validate :finish_cannot_be_earlier_than_start
  
  validates_presence_of :name, :description, :start, :finish

  validates_length_of :name,        in: 2..100
  validates_length_of :description, in: 2..1000

  private

    def finish_cannot_be_earlier_than_start
      unless start.nil? || finish.nil?
        time_error if finish < start
      end
    end

    def time_error
      errors.add(:time_error, 'The fundamental laws of nature prevent time travel')
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_signin!
  before_action :set_event,         only: [:edit, :update, :delete, :destroy]
  after_action  :verify_authorized, only: [:create, :update, :destroy]
  respond_to    :html, :js, :json

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event      = Event.create(event_params)
    @event.user = current_user
    authorize @event
  end

  def update
    @event.update_attributes(event_params)
    authorize @event
  end

  def destroy 
    @event.destroy
    authorize @event
  end

  private

    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:id, :name, :description, :start, :finish,
        :all_day, :user_id)
    end
end

app/views/events/_event_header.html.haml
- content_for :page_header do
  %h1 Events

  %nav
    %ul
      %li
        - if current_user.admin?
          = link_to admin_root_path do
            %button.header-btn.btn-1.btn-1c= icon('eye', 'Admin')
      %li
        = link_to root_path do
          %button.header-btn.btn-1.btn-1c= icon('home', 'Home')
      %li
        - if current_user.admin?
          = link_to new_event_path, remote: true do
            %button.header-btn.btn-1.btn-1c= icon('plus', 'New')

app/views/events/_form.html.haml
= simple_form_for @event, remote: true do |f|
  %ul.errors
  = f.input :name
  = f.input :description, as: :text, input_html: { rows: 4, cols: 30 }
  = f.input :start,   as: :datetimepicker
  = f.input :finish,  as: :datetimepicker
  = f.input :all_day, as: :boolean, label: 'All Day'

  .modal-footer
    %span#hidden-delete{style: 'display:none;'}
      - if policy(@event).destroy?
        = link_to @event, remote: true, method: :delete,
          data: { confirm: 'Are you sure?' }, id: 'destroy' do
          %button.btn.btn-sm.btn-danger= icon('exclamation', 'Delete')

    %span.submit-right
      = hidden_field_tag 'event[user_id]', current_user.id
      - if current_user.admin?
        = f.button :submit, 'Submit', class: 'btn-default'

app/views/events/_modal.html.haml
.modal-dialog.draggable
  .modal-content
    .modal-header
      %button#x-close(type="button" data-dismiss="modal" aria-hidden="true") x
      %h2.modal-title Events
    .modal-body= render 'form' if current_user.admin?

app/views/events/_save.js.haml
= render 'shared/javascript/form_errors', klass: @event if @event.errors.any?

- unless @event.errors.any?
  $('#calendar').fullCalendar( 'refetchEvents' );
  $('#event-modal').modal('hide');

app/views/events/destroy.js.haml
= render 'save'

app/views/events/edit.js.haml
$('#event-modal').html("#{ j render 'modal' }");
$('#hidden-delete').show();
$('#event-modal').modal('show').is(':visible');

= render 'shared/javascript/datetimepicker'
= render 'modal_drag'

app/views/events/index.html.haml
- provide(:title, 'Events')
= render 'event_header'

.row#event-calendar
  .col-md-10.col-md-offset-1#calendar

.row
  .modal.fade#event-modal(tabindex="-1" aria-labelledby="myModalLabel"
    aria-hidden="true")

app/views/events/new.js.haml
$('#event-modal').html("#{ j render 'modal' }");
$('#event-modal').modal('show');

= render 'shared/javascript/datetimepicker'
= render 'modal_drag'