config/routes.rb
Harmonize::Application.routes.draw do
  root 'users#show'

  get '/about', to: 'main_pages#about'

  get    '/signin',  to: 'sessions#new'
  post   '/signin',  to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:new, :create, :destroy]

  resources :accounts, :users

  resources :contacts, except: :edit
  resources :events,   except: :show



  resources :tasks, except: :show do
    get :completed, on: :collection
  end

  resources :users, except: :destroy do
    get :stats, on: :member
  end

  namespace :admin do
    root 'dashboard#index'

    resources :users
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  extend  FriendlyId

  has_secure_password

  friendly_id :handle, use: [:slugged, :finders]

  has_attached_file :avatar, styles: { thumb: '100x100>', regular: '300x300>' },
                            default_url: '/images/avatar/:style/missing.png'

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_many :emails, as: :emailable, dependent: :destroy
  
  has_many :accounts, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :events,   dependent: :destroy
  has_many :tasks,    dependent: :destroy

  validates_uniqueness_of :handle

  validates_presence_of :handle, :password_digest

  validates_length_of :handle,                 in: 3..20
  validates_length_of :first_name, :last_name, maximum: 30

  scope :only_admins, -> { where(admin: true).order(id: :asc) }

  def active_accounts_total
    accounts.active_total
  end

  def inactive_accounts_total
    accounts.inactive_total
  end

  def formatted_name
    if both_names_empty?
      'N/A'
    else
      [first_name, last_name].join(' ')
    end
  end

  private

    def both_names_empty?
      first_name.empty? && last_name.empty?
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'User created'
      redirect_to admin_users_path
    else
      flash.now[:alert] = 'User not created'
      render action: 'new'
    end
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if @user.update(user_params)
      flash[:notice] = 'User updated'
      redirect_to admin_users_path
    else
      flash[:alert] = 'User not updated'
      render action: 'edit'
    end
  end

  def destroy
    if @user == current_user then flash[:alert] = 'Cannot delete thyself!'
    else
      @user.destroy
      flash[:notice] = 'User deleted'
    end
    redirect_to admin_users_path
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:handle, :first_name, :last_name, :password,
        :password_confirmation, :admin)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin!, except: :new
  before_action :set_user, only: [:edit, :update, :show, :stats]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'Account created'
      redirect_to root_path
    else
      flash[:error] = 'Account not created'
      render :new
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'User updated'
      redirect_to admin_users_path
    else
      flash[:alert] = 'User not updated'
      render action: 'edit'
    end
  end

  private

    def set_user
      @user = current_user
    end

    def user_params
      params.require(:user).permit(:handle, :password, :password_confirmation,
        :avatar)
    end
end

app/views/admin/users/_form.html.haml
.row
  .col-md-3
    = simple_form_for [:admin, @user] do |f|
      %legend.bold_title New User
      = f.input :handle, label: 'Username'
      = f.input :password
      = f.input :password_confirmation, label: 'Password Confirmation'
      = f.input :admin
      %p.text-right= f.button :submit, 'Create User', class: 'btn-default'

app/views/admin/users/_navbar.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header#contact-header
      %p.navbar-text.navbar-left= @user.handle
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li= link_to 'Edit User', edit_admin_user_path(@user)
        %li.active
          = link_to 'Delete', admin_user_path(@user), method: :delete,
            data: { confirm: 'Are you sure?' }, id: 'delete-link'

app/views/admin/users/_user.html.haml
= content_tag_for(:tr, user, 'data-id' => user.id)
%tr
  %th.bold_name{ scope: 'row' }= user.id
  
  %td
    = link_to user.handle, [:admin, user]
  
  %td
    = user.admin
  
  %td
    = data_format(user.first_name)
  
  %td
    = data_format(user.last_name)
  
  %td
    = l user.created_at, format: :profile
  
  %td
    = l user.updated_at, format: :profile

app/views/admin/users/_user_header.html.haml
- content_for :page_header do
  %h1 Admin: Users

  %nav
    %ul
      %li
        = link_to admin_root_path do
          %button.header-btn.btn-1.btn-1c= icon('eye', 'Admin')
      %li
        = link_to root_path do
          %button.header-btn.btn-1.btn-1c= icon('home', 'Home')
      %li
        = link_to admin_users_path do
          %button.header-btn.btn-1.btn-1c= icon('users', 'Users')
      %li
        = link_to new_admin_user_path do
          %button.header-btn.btn-1.btn-1c= icon('user', 'New')

app/views/admin/users/edit.html.haml
- provide(:title, "Edit #{@user.handle}")
= render 'user_header'

.row
  .col-md-3
    = simple_form_for [:admin, @user] do |f|
      %legend.bold_title Edit User
      = f.input :handle,     label: 'Username'
      = f.input :first_name, label: 'First Name'
      = f.input :last_name,  label: 'Last Name'
      = f.input :password
      = f.input :password_confirmation, label: 'Password Confirmation'
      = f.input :admin
      %p.text-right= f.button :submit, 'Update User', class: 'btn-default'

app/views/admin/users/index.html.haml
- provide(:title, 'Admin - Users')
= render 'user_header'

.col-md-10
  .panel.panel-default
    .panel-heading Users

    %table.table.table-hover
      %thead
        %tr
          %th{ scope: 'col' } Id
          %th{ scope: 'col' } Handle
          %th{ scope: 'col' } Admin
          %th{ scope: 'col' } First Name
          %th{ scope: 'col' } Last Name
          %th{ scope: 'col' } Created At
          %th{ scope: 'col' } Last Updated
      %tbody= render @users

app/views/admin/users/new.html.haml
- provide(:title, 'Admin - New User')
= render 'user_header'

= render 'form'

app/views/admin/users/show.html.haml
- provide(:title, @user.handle)
= render 'user_header'

= render 'navbar'