config/routes.rb
Harmonize::Application.routes.draw do
  root 'users#show'

  get '/about', to: 'main_pages#about'

  get    '/signin',  to: 'sessions#new'
  post   '/signin',  to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:new, :create, :destroy]

  resources :accounts, :users

  resources :contacts, except: :edit
  resources :events,   except: :show



  resources :tasks, except: :show do
    get :completed, on: :collection
  end

  resources :users, except: :destroy do
    get :stats, on: :member
  end

  namespace :admin do
    root 'dashboard#index'

    resources :users
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  include Formatable
  include Nullable
  include Repeatable
  extend FriendlyId

  belongs_to :user

  friendly_id :name, use: [:slugged, :finders]

  has_one :billing_address,  as: :addressable, dependent: :destroy
  has_one :phone,            as: :phoneable,   dependent: :destroy
  has_one :shipping_address, as: :addressable, dependent: :destroy
  has_one :social_media,     as: :sociable,    dependent: :destroy

  has_many :addresses,       as: :addressable, dependent: :destroy
  has_many :emails,          as: :emailable,   dependent: :destroy

  accepts_nested_attributes_for :billing_address,  reject_if: :all_blank
  accepts_nested_attributes_for :emails,           reject_if: :all_blank
  accepts_nested_attributes_for :phone,            reject_if: :all_blank
  accepts_nested_attributes_for :shipping_address, reject_if: :all_blank
  accepts_nested_attributes_for :social_media,     reject_if: :all_blank

  validates_presence_of :name

  validates_length_of :name,    maximum: 50
  validates_length_of :notes,   maximum: 1000, allow_blank: true
  validates_length_of :website, in: 6..50,     allow_blank: true

  scope :active_total,       -> { where('active is true').count  }
  scope :inactive_total,     -> { where('active is false').count }

  def self.recent_first_billing_address
    recent_first.includes(:billing_address)
  end

  def company_location
    self.billing_address.location
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authorize_admin!, except: [:index, :show]
  before_action :require_signin!
  before_action :set_account,       only: [:show, :update, :destroy  ]
  after_action  :verify_authorized, only: [:create, :update, :destroy]

  def index
    @unpaginated_accounts = Account.recent_first_billing_address
    @accounts = @unpaginated_accounts.page(params[:page])
    pdf = AccountListPdf.new(@unpaginated_accounts)

    respond_to do |format|
      format.html
      format.csv { send_data @accounts.to_csv }
      format.pdf do
        send_data pdf.render, filename: 'account_list.pdf',
          type: 'application/pdf', disposition: 'inline'
      end
    end
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    @account.user = current_user
    authorize @account
 
    if @account.save
      flash[:notice] = 'Account created'
      redirect_to @account
    else
      flash[:alert] = 'Account not created'
      render :new
    end    
  end

  def update
    authorize @account

    if @account.update_attributes(account_params)
      flash[:notice] = 'Account updated'
      redirect_to @account
    else
      flash[:alert] = 'Account not updated'
      redirect_to @account
    end
  end
  
  def destroy
    authorize @account
    @account.destroy
    flash[:notice] = 'Account deleted'
    redirect_to @account
  end

  private
    
    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:name, :website, :notes, :active,

        billing_address_attributes:
          [:id, :street_1, :street_2, :city, :state, :postal_code, :country, :type],

        shipping_address_attributes:
          [:id, :street_1, :street_2, :city, :state, :postal_code, :country, :type],

        emails_attributes:
          [:id, :address],

        phone_attributes:
          [:id, :office, :mobile, :fax, :home, :toll],

        social_media_attributes:
          [:id, :google_plus, :github, :twitter, :skype, :coderwall, :linkedin,
            :facebook])
    end
end

app/views/accounts/_account.html.haml
%tr{ class: (inactive_danger_tr(account)) }

  %td
    = non_programmer_format(account_counter)

  %th.bold_name{ scope: 'row' }
    = link_to account.name, account

  %td
    = data_format(account.website)

  %td
    = data_format(account.company_location)

  %td
    = l account.created_at, format: :index_table

  %td
    = status_format(account.active)

app/views/accounts/_account_form.html.haml
= f.input :name
= f.input :website
= f.input :notes, as: :text, input_html: { rows: 3 }
= f.input :active

app/views/accounts/_account_header.html.haml
- content_for :page_header do
  %h1 Accounts

  %nav
    %ul
      %li
        - if current_user.admin?
          = link_to admin_root_path do
            %button.header-btn.btn-1.btn-1c= icon('eye', 'Admin')
      %li
        = link_to root_path do
          %button.header-btn.btn-1.btn-1c= icon('home', 'Home')
      %li
        = link_to accounts_path do
          %button.header-btn.btn-1.btn-1c= icon('archive', 'All')
      %li
        - if current_user.admin?
          = link_to new_account_path do
            %button.header-btn.btn-1.btn-1c= icon('user', 'New')

app/views/accounts/_account_info.html.haml
.panel.panel-default.panel-borderless
  .panel-heading
    Account Info
    - if policy(@account).update?
      = link_to 'edit', '#', class: 'edit-panel', id: 'ai-panel'

  = render 'account_info_table'

%section#edit-ai-form{ style: 'display:none;' }
  = simple_form_for @account do |f|
    = render 'account_form', f: f

    %span.pull-right
      = link_to 'Cancel', '#', class: 'btn btn-default', id: 'close-ai'
      = f.button :submit

app/views/accounts/_account_info_table.html.haml
%table.table.table-hover#ai-table
  %tbody
    %tr
      %th Account
      %td= @account.name
    %tr
      %th Website
      %td= data_format(@account.website)
    %tr
      %th Location
      %td= data_format(@account.company_location)
    %tr
      %th Notes
      %td= data_format(@account.notes)
    %tr
      %th Created By
      %td= @account.user.handle
    %tr
      %th Created At
      %td= l @account.created_at, format: :profile
    %tr
      %th Last Updated
      %td= l @account.updated_at, format: :profile
    %tr{ class: (inactive_danger_tr(@account)) }
      %th Status
      %td= status_format(@account.active)

app/views/accounts/_account_navbar.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header#contact-header
      %p.navbar-text.navbar-left= @account.name.upcase
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li.active
          - if policy(@account).destroy?
            = link_to 'Delete', @account, method: :delete,
              data: { confirm: 'Are you sure?' }, id: 'delete-link'

app/views/accounts/_form.html.haml
= simple_form_for @account do |f|
  .row
    .col-md-4
      %legend.bold_title General
      = render 'account_form', f: f

      = f.simple_fields_for :emails, @account.emails.build do |builder|
        = render 'shared/email/email_form', builder: builder

      %legend.bold_title Phone
      = f.simple_fields_for :phone, @account.build_phone do |builder|
        = render 'shared/phone/phone_form', builder: builder

    .col-md-5.col-md-offset-1
      %legend.bold_title
        Social Media
        %span.caret.caret-form.pull-right#social-media-caret
      .hidden#social-media-form
        = f.simple_fields_for :social_media,
          @account.build_social_media do |builder|
          = render 'shared/social_media/social_media_form', builder: builder

      %legend.bold_title
        Billing Address
        %span.caret.caret-form.pull-right#billing-address-caret
      .hidden#billing-address-form
        = f.simple_fields_for :billing_address,
          @account.build_billing_address do |builder|
          = render 'shared/address/address_form', builder: builder

      %legend.bold_title
        Shipping Address
        %span.caret.caret-form.pull-right#shipping-address-caret
      .hidden#shipping-address-form
        = f.simple_fields_for :shipping_address,
          @account.build_shipping_address do |builder|
          = render 'shared/address/address_form', builder: builder

      %span.pull-right= f.button :submit

app/views/accounts/index.html.haml
- provide(:title, 'Accounts')
= render 'account_header'

.row
  .col-md-10
    .panel.panel-default
      .panel-heading
        Accounts
        %span.pull-right
          = page_entries_info @accounts
      .panel-body
        = render 'shared/index_panel', url: accounts_path

      %table.table.table-hover
        %thead
          %tr
            %th{ scope: 'col' } #
            %th{ scope: 'col' } Account
            %th{ scope: 'col' } Website
            %th{ scope: 'col' } Location
            %th{ scope: 'col' } Created
            %th{ scope: 'col' } Status
        %tbody= render @accounts

.row
  .col-md-6.col-md-push-3
    = will_paginate @accounts

app/views/accounts/new.html.haml
- provide(:title, 'New Account')
= render 'account_header'

= render 'form'

app/views/accounts/show.html.haml
- provide(:title, @account.name)
= render 'account_header'

= render 'account_navbar'

.row.profile-tables
  .col-md-4= render 'account_info'
  .col-md-4= render 'shared/phone/phone_book', klass: @account
  .col-md-4= render 'shared/email/email',      klass: @account

.row.profile-tables
  .col-md-4= render 'shared/address/billing_address',   klass: @account
  .col-md-4= render 'shared/address/shipping_address',  klass: @account
  .col-md-4= render 'shared/social_media/social_media', klass: @account